# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='model',
            new_name='theme',
        ),
    ]
