# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0002_auto_20160105_0755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='category',
            new_name='color',
        ),
    ]
